//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_urunler()
        {
            this.tbl_urunAciklama = new HashSet<tbl_urunAciklama>();
        }
    
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string UrunUrl { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual tbl_modeller tbl_modeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_urunAciklama> tbl_urunAciklama { get; set; }
    }
}
