//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_birleşim
    {
        public int Id { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> UrunAciklamaId { get; set; }
        public Nullable<int> UrunSiteId { get; set; }
    }
}
