//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urunAciklama
    {
        public int UrunAciklamaId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> UrunMarkaId { get; set; }
        public string isletimSistemi { get; set; }
        public string islemciTip { get; set; }
        public string islemciNesli { get; set; }
        public string ram { get; set; }
        public string diskBoyut { get; set; }
        public string diskTur { get; set; }
        public string ekranBoyut { get; set; }
        public Nullable<int> siteId { get; set; }
    
        public virtual tbl_markalar tbl_markalar { get; set; }
        public virtual tbl_siteler tbl_siteler { get; set; }
        public virtual tbl_urunler tbl_urunler { get; set; }
    }
}
