//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_modeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_modeller()
        {
            this.tbl_urunler = new HashSet<tbl_urunler>();
        }
    
        public int ModelId { get; set; }
        public string ModelNo { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public string ModelResim { get; set; }
        public Nullable<decimal> ModelPuan { get; set; }
    
        public virtual tbl_markalar tbl_markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_urunler> tbl_urunler { get; set; }
    }
}
